name: fhhps-env
channels:
dependencies:
  # Python
  - python>=3.7
  - matplotlib=3.0.2
  - scikit-learn==0.20.2
  - seaborn==0.9.0
  - pip==19.1
  - pip:
      - costsensitive==0.1.1
      - PyLaTeX==1.3.0
      - tzlocal==1.5.1
      # Docs / pytest
      - pytest
      - sphinx
      - sphinx_rtd_theme
      - numpydoc
      - ipython
      - flake8
